#!/bin/bash
#
# demoinstance		Demo Instance
#
# chkconfig: - 99 01
# description: Start instance on openstack
# processname: demoinstance
#
### BEGIN INIT INFO
# Provides: demoinstance
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

# Source function library.
. /etc/init.d/functions

DEMO_DIR=/tmp/DemoInstance/

start() {
        $DEMO_DIR/demo.sh start
        return $?
}

stop() {
        $DEMO_DIR/demo.sh stop
        return $?
}

status() {
        $DEMO_DIR/demo.sh status
        return $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
        ;;
esac
exit $?
