#!/bin/bash
#
# demoinstance          Demo Instance
#
# chkconfig: - 99 01
# description: Start instance on openstack
# processname: demoinstance
#
### BEGIN INIT INFO
# Provides: demoinstance
# Required-Start: $local_fs $network $remote_fs
# Required-Stop: $local_fs $network $remote_fs
# Default-Start: 2 3 4 5
# Default-Stop: 0 1 6
### END INIT INFO

# Source function library.
. /etc/init.d/functions

DEMO_DIR=/tmp/DemoInstance/
USER=demo_instance

if [ -f /etc/sysconfig/demoinstance ]; then
        . /etc/sysconfig/demoinstance
	export PIDFILE
	export LOGFILE
fi


start() {
        su "$USER" -c "$DEMO_DIR/demo.sh start"
        return $?
}

stop() {
        su "$USER" -c "$DEMO_DIR/demo.sh stop"
        return $?
}

status() {
        su "$USER" -c "$DEMO_DIR/demo.sh status"
        return $?
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
        status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage: $0 {start|stop|status}"
        exit 1
        ;;
esac
exit $?
